name: Deploy to Shopify store DEVELOP theme

on:
  push:
    branches:
      - develop

jobs:
  deploy_develop_theme:
    if: ${{ !contains(github.event.head_commit.message, 'no-deploy') }}
    name: Deploy --- DEVELOP Shopify theme
    runs-on: ubuntu-latest
    env:
      SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_THEMEKIT_PASSWORD }}
      SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URI }}
      DESIRED_THEME_ID: ${{ secrets.SHOPIFY_DEVELOP_THEME_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'
      - name: Running npm tasks
        run: |
          echo "DEVELOP THEME DEPLOY TRIGGER EVENT"
          npm ci
          echo "--------- Folder dir files:"
          ls
          npm run webpack:build --if-present
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme
      - name: Deploy
        run: shopify theme push --path ./shopify --nodelete -x templates/*.json sections/*.json locales/*.json config/settings_data.json --theme $DESIRED_THEME_ID -a
